version: '2.3'

services:
  pve:
    extends:
      file: docker-compose.yml
      service: pve
    network_mode: ""
    networks:
      lan_network:

networks:
  lan_network:
    driver: macvlan
    driver_opts:
      parent: enp0s1

volumes:
  cfg_persist:
  data_vz:
