#!/bin/bash

set -xeo pipefail

arg="$1"
[[ -n "$arg" ]] && shift

case "$arg" in
  "")
    docker rm -f pve-ve-release
    docker run --name=pve-ve-release --cgroupns=host \
      --privileged \
      --shm-size=256m \
      --hostname pve-ve-release \
      --publish 8006:8006 \
      -e ROOT_PASSWORD=root1 \
      --volume "$PWD/tmp/proxmox/etc:/var/lib/proxmox-etc" \
      --volume "$PWD/tmp/proxmox/vz:/var/lib/vz" \
      --rm \
      -t pve-ve-release
    ;;

  kill)
    docker kill pve-ve-release
    ;;

  enter)
    exec docker exec -it pve-ve-release /bin/bash
    ;;
esac
