#!/bin/bash

set -xeo pipefail

arg="$1"
shift

case "$arg" in
  "")
    docker rm -f pve-debs
    docker run --name=pve-debs --cgroupns=host \
      --privileged \
      --shm-size=256m \
      --hostname pve-debs \
      --publish 8006:8006 \
      --rm \
      -t pve-debs /sbin/init
    ;;

  builder)
    docker build --build-arg VERSION=7.2 -t builder --target build_env .
    ;;

  enter-builder)
    $0 builder
    docker run --name=pbs_build_env --rm -it -v "$PWD:$PWD" -w "$PWD" builder "$@"
    ;;

  snapshot)
    docker commit pbs_build_env pbs_build_env
    docker tag pbs_build_env builder
    ;;

  enter-pbs-build-env)
    docker run --name=pbs_build_env --rm -it -v "$PWD:$PWD" -w "$PWD" pbs_build_env "$@"
    ;;

  enter-pbs-env)
    docker build --build-arg VERSION=7.2 -t pbs_env --target pbs_env .
    docker run --rm -it -v "$PWD:$PWD" -w "$PWD" pbs_env "$@"
    ;;

  save)
    docker commit pbs_build_env pve-debs
    ;;

  kill)
    docker kill pve-debs
    ;;

  enter)
    exec docker exec -it pve-debs /bin/bash
    ;;
esac
