ARG ARCH=
FROM ${ARCH}debian:bookworm AS toolchain

FROM toolchain as release_env
RUN apt-get -y update && apt-get -y install systemd

ADD /release /release
ADD /dockerfiles /dockerfiles
RUN dockerfiles/scripts/install.bash release \
  proxmox-ve \
  proxmox-backup-restore-image \
  proxmox-firewall \
  pve-edk2-firmware \
  pve-edk2-firmware-legacy \
  pve-edk2-firmware-aarch64 \
  pve-edk2-firmware-riscv

VOLUME /persist \
  /var/lib/vz

ENTRYPOINT ["/dockerfiles/scripts/start.bash"]
