ARG ARCH=
FROM ${ARCH}debian:bookworm AS toolchain

RUN apt-get -y update && \
  apt-get -y install \
    build-essential git-core \
    lintian pkg-config quilt patch cargo \
    nodejs node-colors node-commander \
    libudev-dev libapt-pkg-dev \
    libacl1-dev libpam0g-dev libfuse3-dev \
    libsystemd-dev uuid-dev libssl-dev \
    libclang-dev libjson-perl libcurl4-openssl-dev \
    dh-exec wget devscripts rsync patchelf xmlto jq sudo meson

ENV RUSTUP_TOOLCHAIN=nightly
RUN wget https://static.rust-lang.org/rustup/rustup-init.sh && \
  chmod +x rustup-init.sh && \
  ./rustup-init.sh -y --default-toolchain "$RUSTUP_TOOLCHAIN"

WORKDIR /src
RUN for tool in /root/.cargo/bin/*; do ln -vsf $tool /usr/bin/; done
RUN cargo install debcargo
RUN /usr/bin/rustc --version
RUN git config --global user.email "docker@compile.dev" && \
  git config --global user.name "Docker Compile"
RUN ls -sf /bin/true /usr/share/cargo/bin/dh-cargo-built-using

FROM toolchain as build_env
RUN apt-get -y install libglib2.0-dev graphviz

ADD /scripts .
ADD /repos .
SHELL ["/bin/bash", "-c"]
RUN ./scripts/repo.bash dh-cargo dpkg_{build,install}
RUN ./scripts/repo.bash ifupdown2 make_dinstall
RUN ./scripts/repo.bash pve-eslint make_dinstall
RUN ./scripts/repo.bash proxmox-widget-toolkit make_dinstall
# RUN ./scripts/repo.bash libqb "make_dinstall . . DEB_BUILD_OPTIONS=nocheck"
RUN ./scripts/repo.bash corosync-pve make_dinstall
# # broken: if_installed corosync-qdevice || dinstall corosync-qdevice
RUN ./scripts/repo.bash ksm-control-daemon make_dinstall
RUN ./scripts/repo.bash vncterm make_dinstall
RUN ./scripts/repo.bash extjs make_dinstall
RUN ./scripts/repo.bash libjs-qrcodejs make_dinstall
RUN ./scripts/repo.bash proxmox-mini-journalreader make_dinstall
RUN ./scripts/repo.bash proxmox
RUN ./scripts/repo.bash pve-xtermjs "make_dinstall termproxy" "make_dinstall xterm.js"
RUN ./scripts/repo.bash proxmox-i18n make_deb rm
RUN ./scripts/repo.bash novnc-pve make_dinstall
RUN ./scripts/repo.bash lxcfs make_dinstall
# RUN ./scripts/repo.bash lxc make_dinstall
RUN ./scripts/repo.bash pve-apiclient make_dinstall
RUN ./scripts/repo.bash libpve-u2f-server-perl make_dinstall
# RUN ./scripts/repo.bash pve-lxc-syscalld make_dinstall
# RUN ./scripts/repo.bash proxmox-mail-forward make_dinstall
RUN ./scripts/repo.bash proxmox-websocket-tunnel dpkg_{build,install}

RUN ./scripts/repo.bash perlmod "dpkg_build perlmod-bin" "dpkg_install"
RUN ./scripts/repo.bash proxmox-resource-scheduling
RUN ./scripts/repo.bash proxmox-ve-rs
RUN ./scripts/repo.bash proxmox-perl-rs "make_dinstall pve-rs ."
RUN ./scripts/repo.bash pve-common make_dinstall
RUN ./scripts/repo.bash proxmox-acme make_dinstall

# if_installed libproxmox-rs-perl || dinstall proxmox-perl-rs pve-rs pve-deb common-deb
# if_installed libpve-common-perl || dinstall pve-common
# if_installed proxmox-backup-client || dinstall proxmox-backup . deb-all
# if_installed libproxmox-backup-qemu0-dev || dinstall proxmox-backup-qemu
# if_installed pve-qemu-kvm || dinstall pve-qemu || if_installed pve-qemu-kvm
# if_installed spiceterm || dinstall spiceterm
# if_installed pve-edk2-firmware || dinstall pve-edk2-firmware
# # broken: if_installed criu || dinstall criu criu dinstall