ARG ARCH=
FROM ${ARCH}debian:bookworm AS toolchain

RUN apt-get -y update && \
  apt-get -y install \
    build-essential git-core \
    lintian pkg-config quilt patch cargo \
    nodejs node-colors node-commander \
    libudev-dev libapt-pkg-dev \
    libacl1-dev libpam0g-dev libfuse3-dev \
    libsystemd-dev uuid-dev libssl-dev \
    libclang-dev libjson-perl libcurl4-openssl-dev \
    dh-exec wget devscripts rsync patchelf xmlto jq sudo meson \
    libglib2.0-dev graphviz

ENV RUSTUP_TOOLCHAIN=stable \
  CARGO_HOME=/cargo \
  RUSTUP_HOME=/rustup \
  PATH="/cargo/bin:$PATH"
RUN wget https://static.rust-lang.org/rustup/rustup-init.sh && \
  chmod +x rustup-init.sh && \
  ./rustup-init.sh -y --default-toolchain "stable" && \
  rustup toolchain install "nightly" && \
  cargo install debcargo && \
  rustc --version

# Not required in trixie
RUN cd /tmp && \
  wget http://ftp.us.debian.org/debian/pool/main/a/asciidoc/asciidoc-common_10.2.1-1_all.deb && \
  wget http://ftp.us.debian.org/debian/pool/main/a/asciidoc/asciidoc-base_10.2.1-1_all.deb && \
  apt install -y $PWD/asciidoc-*.deb

# Link /cargo/bin to /usr/local/bin
RUN ln -s /cargo/bin/* /usr/local/bin/
ADD dockerfiles/env/dpkg-to-apt.bash /usr/local/bin/dpkg

WORKDIR /src
RUN git config --system user.email "docker@compile.dev" && \
  git config --system user.name "Docker Compile"

FROM toolchain as build_env

ADD /scripts .
ADD /repos .
SHELL ["/bin/bash", "-c"]
RUN ./scripts/repo.bash dh-cargo dpkg_{build,install} && ln -sf /bin/true /usr/share/cargo/bin/dh-cargo-built-using
RUN ./scripts/repo.bash ifupdown2 make_dinstall
RUN ./scripts/repo.bash pve-eslint make_dinstall
RUN ./scripts/repo.bash proxmox-widget-toolkit make_dinstall
# RUN ./scripts/repo.bash libqb "make_dinstall . . DEB_BUILD_OPTIONS=nocheck"
RUN ./scripts/repo.bash corosync-pve make_dinstall
# # broken: if_installed corosync-qdevice || dinstall corosync-qdevice
RUN ./scripts/repo.bash ksm-control-daemon make_dinstall
RUN ./scripts/repo.bash vncterm make_dinstall
RUN ./scripts/repo.bash extjs make_dinstall
RUN ./scripts/repo.bash libjs-qrcodejs make_dinstall
RUN ./scripts/repo.bash proxmox-mini-journalreader make_dinstall
RUN ./scripts/repo.bash pve-xtermjs "make_dinstall termproxy" "make_dinstall xterm.js"
RUN ./scripts/repo.bash proxmox-i18n make_deb dpkg_install
RUN ./scripts/repo.bash novnc-pve make_dinstall
RUN ./scripts/repo.bash lxcfs make_dinstall
RUN ./scripts/repo.bash lxc make_dinstall
RUN ./scripts/repo.bash pve-apiclient make_dinstall
RUN ./scripts/repo.bash libpve-u2f-server-perl make_dinstall
RUN ./scripts/repo.bash pve-lxc-syscalld make_dinstall
# RUN ./scripts/repo.bash proxmox-mail-forward make_dinstall
RUN ./scripts/repo.bash --nightly proxmox-websocket-tunnel dpkg_{build,install}

RUN ./scripts/repo.bash perlmod "dpkg_build perlmod-bin" "dpkg_install"
RUN ./scripts/repo.bash proxmox-perl-rs "make_deb common/pkg" "make_deb pve-rs" dpkg_install
RUN ./scripts/repo.bash pve-common make_dinstall
RUN ./scripts/repo.bash proxmox-acme make_dinstall
# Not needed? RUN ./scripts/repo.bash pxar make_build strip_cargo "dpkg_build build/pxar"
RUN ./scripts/repo.bash proxmox-backup make_dinstall
RUN dpkg -i release/proxmox-backup/proxmox-backup-file-restore_3.3.2-2_arm64.deb
RUN ./scripts/repo.bash proxmox-backup-qemu make_dinstall
RUN ./scripts/repo.bash pve-qemu make_dinstall
RUN ./scripts/repo.bash pve-edk2-firmware make_dinstall
RUN ./scripts/repo.bash spiceterm make_dinstall
# Not needed: RUN ./scripts/repo.bash proxmox-kernel-helper make_deb
# Not needed: RUN ./scripts/repo.bash proxmox-archive-keyring make_deb
RUN ./scripts/repo.bash pve-docs "make . . gen-install"
RUN ./scripts/repo.bash pve-docs make_dinstall
RUN ./scripts/repo.bash pve-access-control "make src . install NODOC=1"
RUN ./scripts/repo.bash pve-cluster "make_dinstall . . DEB_BUILD_OPTIONS=noparallel"
RUN ./scripts/repo.bash pve-access-control make_dinstall
RUN ./scripts/repo.bash librados2-perl make_dinstall
RUN ./scripts/repo.bash pve-storage make_dinstall
RUN ./scripts/repo.bash pve-guest-common make_dinstall
RUN ./scripts/repo.bash pve-http-server make_dinstall
RUN ./scripts/repo.bash pve-network make_dinstall
RUN ./scripts/repo.bash pve-firewall make_dinstall
RUN ./scripts/repo.bash pve-container make_dinstall
RUN ./scripts/repo.bash pve-ha-manager make_dinstall
RUN ./scripts/repo.bash qemu-server make_dinstall
# Depends: libpve-notify-perl but it is not installable
# Depends: libpve-storage-perl (>= 8.3.5) but it is not installable
# Depends: pve-container but it is not installable
# Depends: pve-doc-generator (>= 8.3.2) but it is not installable
# Depends: qemu-server (>= 8.0~~) but it is not installable
RUN ./scripts/repo.bash pve-manager make_dinstall
RUN ./scripts/repo.bash proxmox-ve make_deb

# if_installed proxmox-backup-client || dinstall proxmox-backup . deb-all
# if_installed libproxmox-backup-qemu0-dev || dinstall proxmox-backup-qemu
# if_installed pve-qemu-kvm || dinstall pve-qemu || if_installed pve-qemu-kvm
# if_installed spiceterm || dinstall spiceterm
# if_installed pve-edk2-firmware || dinstall pve-edk2-firmware
# # broken: if_installed criu || dinstall criu criu dinstall