ARG ARCH=
FROM ${ARCH}debian:bookworm AS toolchain

FROM toolchain as run_env
RUN apt-get -y update && apt-get -y install runit

ADD /dockerfiles/run /scripts
RUN scripts/install.bash release \
  proxmox-ve \
  proxmox-backup-restore-image \
  proxmox-firewall \
  pve-edk2-firmware \
  pve-edk2-firmware-legacy \
  pve-edk2-firmware-aarch64 \
  pve-edk2-firmware-riscv

VOLUME /var/log \
  /var/lib/rrdcached/db \
  /var/lib/pve-cluster \
  /var/lib/pve-manager \
  /var/lib/vz
