ARG ARCH=
FROM ${ARCH}debian:bookworm AS toolchain

RUN apt-get -y update && \
  apt-get -y install \
    build-essential git-core \
    lintian pkg-config quilt patch cargo \
    nodejs node-colors node-commander \
    libudev-dev libapt-pkg-dev \
    libacl1-dev libpam0g-dev libfuse3-dev \
    libsystemd-dev uuid-dev libssl-dev \
    libclang-dev libjson-perl libcurl4-openssl-dev \
    dh-exec wget devscripts rsync patchelf xmlto jq sudo meson

RUN wget https://static.rust-lang.org/rustup/rustup-init.sh && \
  chmod +x rustup-init.sh && \
  ./rustup-init.sh -y --default-toolchain nightly

WORKDIR /src

ENV RUSTUP_TOOLCHAIN=stable
RUN for tool in /root/.cargo/bin/*; do ln -vsf $tool /usr/bin/; done
RUN cargo install debcargo
RUN /usr/bin/rustc --version
RUN git config --global user.email "docker@compile.dev" && \
  git config --global user.name "Docker Compile"
ENV PATH=/root/.cargo/bin:$PATH

FROM toolchain as build_env

ADD /scripts .
ADD /repos .
SHELL ["/bin/bash", "-c"]
RUN ./scripts/repo.bash dh-cargo dpkg_{build,install}
RUN ./scripts/repo.bash ifupdown2 make_dinstall
RUN ./scripts/repo.bash pve-eslint make_dinstall
RUN ./scripts/repo.bash proxmox-widget-toolkit make_dinstall
# RUN apt-get install -y libglib2.0-dev graphviz
# RUN ./scripts/repo.bash libqb "make_dinstall . . DEB_BUILD_OPTIONS=nocheck"
RUN ./scripts/repo.bash corosync-pve make_dinstall
# # broken: if_installed corosync-qdevice || dinstall corosync-qdevice
RUN ./scripts/repo.bash ksm-control-daemon make_dinstall
RUN ./scripts/repo.bash vncterm make_dinstall
RUN ./scripts/repo.bash extjs make_dinstall
RUN ./scripts/repo.bash libjs-qrcodejs make_dinstall
RUN ./scripts/repo.bash proxmox-mini-journalreader make_dinstall
RUN ./scripts/repo.bash pve-xtermjs "make_dinstall termproxy" "make_dinstall xterm.js"
# if_installed pve-xtermjs || dpkg_buildpackage pve-xtermjs
# if_installed pve-i18n || dinstall proxmox-i18n . deb
# if_installed swtpm || dpkg_buildpackage swtpm
# if_installed novnc-pve || dinstall novnc-pve
# if_installed lxcfs || dinstall lxcfs
# if_installed lxc-pve || dinstall lxc
# if_installed libpve-apiclient-perl || dinstall pve-apiclient
# if_installed libpve-u2f-server-perl || dinstall libpve-u2f-server-perl
# if_installed pve-lxc-syscalld || dinstall pve-lxc-syscalld
# if_installed proxmox-mail-forward || dinstall proxmox-mail-forward
# if_installed proxmox-websocket-tunnel || dpkg_buildpackage proxmox-websocket-tunnel

# if_installed libproxmox-rs-perl || dinstall proxmox-perl-rs pve-rs pve-deb common-deb
# if_installed libpve-common-perl || dinstall pve-common
# if_installed libproxmox-acme-perl libproxmox-acme-plugins || dinstall proxmox-acme
# if_installed proxmox-backup-client || dinstall proxmox-backup . deb-all
# if_installed libproxmox-backup-qemu0-dev || dinstall proxmox-backup-qemu
# if_installed pve-qemu-kvm || dinstall pve-qemu || if_installed pve-qemu-kvm
# if_installed spiceterm || dinstall spiceterm
# if_installed pve-edk2-firmware || dinstall pve-edk2-firmware
# # broken: if_installed criu || dinstall criu criu dinstall