#!/bin/bash

if [[ ! -e /run/pve-cluster.pid ]]; then
  echo "FIREWALL: The pve-cluster is not yet started!"
  exit 1
fi

export RUST_LOG_STYLE=SYSTEMD
export RUST_LOG=warn

exec /usr/libexec/proxmox/proxmox-firewall start -f
