#!/bin/bash

if [[ -n "$TZ" ]]; then
  echo "$TZ" > /etc/timezone
fi

mkdir -p /run/lock /run/network
mkdir -p /var/lib/rrdcached/db/
chmod 777 /run/lock

cat <<EOF > /etc/network/interfaces.d/vmbr0
auto vmbr0
iface vmbr0 inet static
        address 192.168.99.1/24
        bridge-ports none
        bridge-stp off
        bridge-fd 0
EOF
ifreload -a

# /run/pve-cluster.pid
exec /usr/bin/pmxcfs -f -l
