on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - .github/workflows/*.yaml
  pull_request:
  workflow_dispatch:

jobs:
  docker-build:
    timeout-minutes: 360
    runs-on: ${{ matrix.runs_on }}
    continue-on-error: ${{ matrix.continue-on-error || false }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runs_on: ubuntu-24.04-arm
            arch: arm64
          - runs_on: ubuntu-24.04
            arch: amd64
            continue_on_error: true
    env:
      ARCH: ${{ matrix.arch }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Remove unwanted dependencies
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune -a
    - name: Free disk space after cleanup
      run: df -h
    - name: Set repository name
      if: vars.DOCKERHUB_TEST_REGISTRY
      run:
        echo "REGISTRY=${{ vars.DOCKERHUB_TEST_REGISTRY }}" >> $GITHUB_ENV;
        if [[ -n "${{ github.event.pull_request.number }}" ]]; then
          echo "TAG=github-pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV;
        else
          echo "TAG=ref-${{ github.ref_name }}" >> $GITHUB_ENV;
        fi
    - name: Compile and release for ${{matrix.arch}}
      id: compile_cmd
      run:
        ./release.bash "${{ env.REGISTRY }}:${{ env.TAG }}" build-tgz build-image
      continue-on-error: ${{ matrix.continue_on_error || false }}

    # Push Artifacts to GitHub
    - uses: actions/upload-artifact@v4
      if: success() && steps.compile_cmd.outcome == 'success'
      with:
        name: proxmox-ve-${{ matrix.arch }}
        path: release/*.tgz

    # Push to DockerHub
    - name: Login to Docker Hub
      if: success() && steps.compile_cmd.outcome == 'success' && vars.DOCKERHUB_TEST_REGISTRY
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_TEST_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TEST_TOKEN }}
    - name: Run docker push for ${{matrix.arch}}
      if: success() && steps.compile_cmd.outcome == 'success' && vars.DOCKERHUB_TEST_REGISTRY
      run:
        ./release.bash "${{ env.REGISTRY }}:${{ env.TAG }}" push-image
    - name: Free disk space after build
      if: always()
      run: df -h

  manifest:
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set repository name
      if: vars.DOCKERHUB_TEST_REGISTRY
      run:
        echo "REGISTRY=${{ vars.DOCKERHUB_TEST_REGISTRY }}" >> $GITHUB_ENV;
        if [[ -n "${{ github.event.pull_request.number }}" ]]; then
          echo "TAG=github-pr-${{ github.event.pull_request.number }}" >> $GITHUB_ENV;
        else
          echo "TAG=ref-${{ github.ref_name }}" >> $GITHUB_ENV;
        fi
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_TEST_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TEST_TOKEN }}
    - name: Create manifest
      if: vars.DOCKERHUB_TEST_REGISTRY
      run:
        ./release.bash "${{ env.REGISTRY }}:${{ env.TAG }}" manifest
    - name: Comment image name on PR
      if: vars.DOCKERHUB_TEST_REGISTRY && github.event_name == 'pull_request'
      env:
        REGISTRY: ${{ env.REGISTRY }}
        TAG: ${{ env.TAG }}
      uses: actions/github-script@v7
      with:
        script: |
          const imageName = `${{ env.REGISTRY }}:${{ env.TAG }}`;
          const body = `✅ Docker image pushed: \`${imageName}\``;

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: body
          });
